#!/bin/bash

#run: wget https://raw.githubusercontent.com/aeropedia/script/master/ajenti/install -O - | bash –

sudo apt-get update
sudo apt-get -y upgrade

wget -O- https://raw.github.com/Eugeny/ajenti/master/scripts/install-ubuntu.sh | sudo sh
