#!/bin/bash

#run: wget https://raw.githubusercontent.com/aeropedia/script/master/zentyal/install -O - | sh –

#check if it's root
if [[ $UID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

sudo apt-get update
sudo apt-get -y upgrade
sudo echo "deb http://archive.zentyal.org/zentyal 3.4 main extra" >> /etc/apt/sources.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 10E239FF
wget -q http://keys.zentyal.org/zentyal-3.4-archive.asc -O- | sudo apt-key add -
sudo apt-get update
sudo apt-get -y install zentyal
