#!/bin/bash

#run: wget https://raw.githubusercontent.com/aeropedia/script/master/node/install -O - | bash

sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get install apache2 php5 mysql php5-intl php5-curl php5-gd php5-ldap xapian-core xapian-omega xapian-bindings
