#!/bin/bash

#run: wget https://raw.githubusercontent.com/aeropedia/script/master/xo/install -O - | bash –

sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get -y install build-essential
sudo apt-get -y install curl openssl libssl-dev git

git clone https://github.com/joyent/node.git
cd node
git checkout v0.10.24
./configure
make
sudo make install
